### ISSUE TITLE
How to use a mapper.query?

### ISSUE THREAD

**Issue by LucasBadico** [awslabs/dynamodb-data-mapper-js#101]
```js
this.mapper.query(
   MyObjClass, { key: 'value' }, { indexName: index }
)
```

how to use a filter on mapper.query?

**Comment by jeskew** [comment]
You can supply a [filter](https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-data-mapper/interfaces/queryoptions.html#filter) as part of the `options` parameter (the third parameter that currently has an `indexName`)
