### ISSUE TITLE
unprocessed record handling in BatchWrite.ts

### ISSUE THREAD

**Issue by anupareek** [awslabs/dynamodb-data-mapper-js#106]
Hi @jeskew , 

Thank you for maintaining the repo. 
I see that in BatchWrite.ts, we are manually handling the unprocessed records and sending them back to AWS for retry. 
Why do we need this logic when we already have an exponential backoff logic that is supported by AWS-SDK?

**Comment by jeskew** [comment]
Hi @anupareek,

Batch operations are a bit unique in the way they process errors. Per the [DynamoDB developer guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.BatchOperations), a "batch operation can tolerate the failure of individual requests in the batch." What this means is that the SDK will only retry requests where **all** individual requests failed. If you send a `BatchWriteItem` request with 25 items and each one of them is throttled, then the SDK will retry the whole batch request. If 1 item is written and 24 are throttled, then DynamoDB will report a success with some unprocessed records, and the SDK will not retry.

**Comment by anupareek** [comment]
Thanks @jeskew !
