### ISSUE TITLE
How does batchPut return inserted records?

### ISSUE THREAD

**Issue by GaneshMisal** [awslabs/dynamodb-data-mapper-js#108]
Hi,

First of all, thanks for this library!

I wanted to know, how is DataMapper returning the inserted records when I call batchPut()? because when I try the same thing with DynamoDb's batchWriteItem, It doesn't return anything when records are inserted. So what does batchPut() return? does it return the records which are sent in Request? or It is handling it any other way?

Thanks in advance!!
Awaiting your valuable response.

**Comment by jeskew** [comment]
It returns records as they are successfully written. The writing iterator splits the input into batches of 25 or fewer and applies exponential backoff to writes to a table when one or more records from that table are returned as unprocessed, so it needs to keep track of what requests are outstanding and which have succeeded.
