### ISSUE TITLE
Marshall DynamoDB AttributeValues to Annotated Class

### ISSUE THREAD

**Issue by gambit66** [awslabs/dynamodb-data-mapper-js#109]
I would like convert DynamoDB AttributeValues received from a Dynamo DB Stream event to an annotated model class. The auto marshaller does a good job of this with the exception of Date types which are numbers. I guess I can use the standard data marshaller but I need a schema. Internally this must done when using the data mapper with annotated classes. Any tips on how I can achieve this without a schema?

**Comment by jeskew** [comment]
Without a schema, unmarshalled data will directly reflect the constraints of DynamoDB’s data model. All properties will be unmarshalled into an `UnmarshalledAttributeValue` defined as follows:

```typescript
type UnmarshalledAttributeValue =
    number |
    string |
    Uint8Array |
    boolean |
    null |
    Set<string> |
    Set<number> |
    Set<Uint8Array> |
    Array<UnmarshalledAttributeValue> |
    Map<string, UnmarshalledAttributeValue>;
```

Other data types supported by the data marshaller, such as dates, tuples, and typed lists, require a schema.

Perhaps if you know which fields are meant to contain dates, you can use the auto marshaller for the majority of the document and then manually adjust some fields to be dates? If the data was serialized with the data marshaller, then the date fields will contain epoch second time stamps.

**Comment by gambit66** [comment]
Hi @jeskew, thanks for taking the time to respond. I actually did use the auto marshaller and replaced the dates manually but was hoping there was a more elegant way. I was thinking it was possible because the dynamodb-data-mapper-js library is able to do this marshalling with the annotated classes and doesn't require a schema.

**Comment by jeskew** [comment]
The annotated class is used to generate a schema. If you use the `@attribute` annotation on at least one class property, then the class will have an additional non-enumerable property accessible via the `require(‘@aws/dynamodb-data-mapper’).DynamoDbSchema` symbol that contains the schema.
