### ISSUE TITLE
Expression predicate to check if a string array subject contains a specific element

### ISSUE THREAD

**Issue by pabhishek-deloitte** [awslabs/dynamodb-data-mapper-js#110]
Consider that a record has an element category which is an array of strings. Is there an expression predicate that allows me to filter only the records of a specific category.

**Comment by jeskew** [comment]
Looking at [the DynamoDB comparison function reference](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html), I don't see a way to execute this query on a list of strings. Can the record schema be modified to use a *set* of strings instead? This would allow you to use the [`contains` expression predicate](https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-expressions/globals.html#contains).

**Comment by pabhishek-deloitte** [comment]
Hey, this helps. I will work on figuring a way out. Btw, do you have an idea why the `contains` predicate would be missing in the [docs](https://github.com/awslabs/dynamodb-data-mapper-js/tree/master/packages/dynamodb-expressions). There were no exports for predicate in the `@aws/dynamodb-expressions` npm package. I am using v0.7.3

**Comment by pabhishek-deloitte** [comment]
Hey @jeskew, ignore the earlier comment. This was resolved on updating the package and the `contains` predicate did the job.
