### ISSUE TITLE
DataMapper.query yields 'ValidationException: Query condition missed key schema element' exception

### ISSUE THREAD

**Issue by denver-HJS** [awslabs/dynamodb-data-mapper-js#120]
I'm trying to query a Global Secondary Index, but I'm unable to get beyond this exception.

The GSI is based on a post's scheduled end date in the form of `YYYY-MM-DD`.

When I try to build the query like so:

    function getQueryPaginator( dataMapper: DataMapper, startKey: { [ key: string ]: any } ): QueryPaginator<Load> {
      const today: Date = new Date();
      const partitionKey: string = `${today.getFullYear()}-${today.getMonth() + 1}-${today.getDate()}`;
    
      const queryOptions: QueryOptions = {
        indexName: 'PostingExpiryIndex',
        limit: 25
      };
    
      return dataMapper.query(
        Load,
        {
          partitionKey: partitionKey
        },
        queryOptions
      ).pages();
    }

And use it:

    const paginator: QueryPaginator<Load> = getQueryPaginator( dataMapper, lastEvaluatedKey );
    
        for await ( const page of paginator ) {
          try {
            const loadsBatch: Array<Load> = [];
            page.forEach( ( load: LoadInterface ) => {
              // do some logic...
              loadsBatch.push( Object.assign( new Load(), load ) );
            } );
            dataMapper.batchPut( loadsBatch );
          } catch ( e ) {
            log.error( `Error occurred while processing expired loads: ${e}` );
            await handleError( e );
          }
        }

I get the following exception:

> ValidationException: Query condition missed key schema element
>     at Request.extractError (/Users/myworkspace/node_modules/aws-sdk/lib/protocol/json.js:48:27)

I am however able to query and fetch values using the AWS Document client's equivalent API:

    var params = {
        TableName: 'loads',
        IndexName: 'PostingExpiryIndex', // optional (if querying an index)
        KeyConditionExpression: 'postingEndDate = :value', // a string representing a constraint on the attribute
        ExpressionAttributeValues: { // a map of substitutions for all attribute values
          ':value': '2018-10-26'
        }
    };
    docClient.query(params, function(err, data) {
        if (err) ppJson(err); // an error occurred
        else ppJson(data); // successful response
    });

  [1]: https://github.com/awslabs/dynamodb-data-mapper-js

**Comment by jeskew** [comment]
In the first example, is `partitionKey` being used as the property name? In the third example, `postingEndDate` is used instead.

**Comment by denver-HJS** [comment]
`partitionKey` is being used as the value of the partitionKey for the index that I'm querying by.

Isn't that the requirement according to the docs? --
```
import {between} from '@aws/dynamodb-expressions';

  const keyCondition = {
      partitionKey: 'foo',
      rangeKey: between(10, 99),
  };
```
> The key condition must target a single value for the partition key.

I guess my assumption was that by including the `indexName` in the query options, that the library would use that to infer the indexed property name based on the annotations in the class schema.

**Comment by jeskew** [comment]
The property names in `keyCondition` should be the properties used to issue a query. Given a class like the following:

```typescript
@table("my-table")
class MyClass {
    @autoGeneratedHashKey()
    foo: string;
}
```

The key condition would be `{foo: < key value sought >}`.

**Comment by denver-HJS** [comment]
I see, thank you for the clarification. Updating the`keyCondition` to use the GSI class property instead of the fixed 'partitionKey' property name fixed it.

Just a thought, but it might be helpful to include the class snippet you have above with the query documentation for additional context. Anyway, thanks again!
