### ISSUE TITLE
TS error in @aws/dynamodb-data-mapper/build/constants.d.ts

### ISSUE THREAD

**Issue by gr3w2** [awslabs/dynamodb-data-mapper-js#121]
Hi there!
In the file `@aws/dynamodb-data-mapper/build/constants.d.ts` you have TS error: "error TS2304: Cannot find name 'AsyncIterable'."

package version: 0.7.3

**Comment by ryanmitts** [comment]
If you are targeting Node 8 or later (es2017), then add the following to the lib section of your tsconfig file (this works for me).

Looks like this library has a polyfill for it anyway.

```
"lib": [
      "es2017",
      "esnext.asynciterable"
    ],
```
