### ISSUE TITLE
Highest Range Key query

### ISSUE THREAD

**Issue by digitaldivvy** [awslabs/dynamodb-data-mapper-js#137]
Simple question

HashKey: String
RangeKey: Number

There is a lack of documentation so asking on here.

What's the best way to get the row with the highest RangeKey for a given HashKey.

An option is to query on HashKey and use ScanIndexForward false, and get the first row, then quit. Is this the optimal way? I know that there is no 'max' function.

Thanks!

**Comment by digitaldivvy** [comment]
## Solutions

Anyone?

**Comment by jeskew** [comment]
Querying the hash key with a limit of 1 and `ScanIndexForward` is the optimal way to get the highest value for the sort key.

**Comment by cloudsolver** [comment]
const options={"limit":1, "scanIndexForward": false}

**Comment by digitaldivvy** [comment]
Thanks everyone and @jeskew !!

**Comment by 4EverEndeavor** [comment]
Follow up question here: I'm trying to find the min rangekey item instead, setting scanIndexForward to true, but it seems that the query is taking a really long time. My guess here is that it's going through every rangekey value before arriving at the last one. Is there a better way to do this?
