### ISSUE TITLE
Configuration with webpack and babel 7 - metadata missing

### ISSUE THREAD

**Issue by akleiber** [awslabs/dynamodb-data-mapper-js#140]
Hi, 

thank you for this package - it looks really promising!
I was able to set this up with webpack and babel. However I always get the error 

> Properties of type Any may not be used as index or table keys. If you are relying on automatic type detection and have encountered this error, please ensure that the 'emitDecoratorMetadata' TypeScript compiler option is enabled. Please see https://www.typescriptlang.org/docs/handbook/decorators.html#metadata for more information on this compiler option.

I setup typescript with `emitDecoratorMetadata: true` but I think babel just removes those lines or they are never generated?

My setup:

babel.config.js
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
        loose: true,
        targets: {
          node: '8.10',
        },
      },
    ],
    '@babel/typescript',
  ],
  plugins: [
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    '@babel/plugin-proposal-async-generator-functions',
    '@babel/plugin-transform-async-to-generator',
  ],
}
```

webpack.config.js
```
const path = require('path')
const slsw = require('serverless-webpack')

const { profile, stage } = slsw.lib.options

module.exports = {
  target: 'node',
  mode: slsw.lib.webpack.isLocal || profile !== 'production' || stage !== 'prod' ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: 'source-map',
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json'],
    modules: ['node_modules'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  externals: ['aws-sdk'],
  module: {
    rules: [
      {
        test: /\.(ts|js)x?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
    ],
  },
  stats: {
    colors: true,
  },
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/types/*"]
    }
  },
  "include": ["src/**/*"]
}
```

Is it even possible to have the typescript metadata with babel?

**Comment by tpennetta** [comment]
@akleiber 
As a matter of curiosity can I ask why you are using this library with Webpack/Babel? This sounds like you want to serve this library to the front-end but wouldn't that be a big security risk? Allowing clients which download the page to easily see your table names, structures, AWS config options, etc.?

Perhaps I am completely wrong in my assumption that you are using this in the backend, I just wasnt sure why you would go through the hassle of webpack, when Typescript is a transpiler itself?

**Comment by chrisradek** [comment]
@tpennetta 
One reason you might want to use webpack for a node.js project is if you're deploying to Lambda. You can use webpack to create a bundle that includes only what your lambda app actually uses, instead of everything in your node_modules directory. This can significantly cut down the final size of your lambda function.

**Comment by akleiber** [comment]
@tpennetta Hi. As @chrisradek said, we use the webpack/babel (now tsc) setup to transpile and pack our node code for Lambda @ node.js 8.10

I will close this issue, because it is resolved by using the typescript compiler instead of babel.

**Comment by leonardfactory** [comment]
Sorry if this already closed, howevever I'd like to say that, encountering the same problem, I've developed a babel plugin to emit decorator metadata using `@babel/preset-typescript`: https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata

Hoping to help someone with the same problem founding this issue! 👍
