### ISSUE TITLE
Question about general future roadmap

### ISSUE THREAD

**Issue by breath103** [awslabs/dynamodb-data-mapper-js#15]
Hi i'm the maintainer of [DynamoDB-TypeORM](https://github.com/balmbees/dynamo-typeorm), and it seems to happen what you guys building here is pretty similar. 
As an big fan and customer of AWS, we'd love to see you guys providing tools for us, but also wanna make sure how you guys gonna develop this
Can you checkout work on our side and share your future plans about dynamodb-data-mapper-js? it would really helpful us to decide how we gonna invest our resources.

**Comment by jeskew** [comment]
Hi @breath103,

Cool project! It looks like we both started work on these libraries at the same time (based on https://github.com/awslabs/dynamodb-data-mapper-js/commit/3c115b6e686017e7532f15b84155a8e4499a9fb5 and https://github.com/balmbees/dynamo-typeorm/commit/f2b459dbbc0dea96f50164cc6149e371e39ee97b) and that both were inspired by [TypeORM](https://github.com/typeorm/typeorm) (if I'm not reading too much into your project's name).

Just based on the README, I think the biggest differences right now are that DynamoDB-TypeORM supports more features (table creation/dropping, batch operations) while this library has a more granular type system (including strongly-typed subdocuments; typed lists, sets, and maps; and tuples). This project is going to continue to be developed and supported, but we haven't reached 1.0 yet, so the API can change if we get strong customer feedback pointing us in that direction.

Is there anything you'd like to see added to this library? It's still under active development, so feedback about what features you would consider important would be very welcome.

**Comment by breath103** [comment]
Thanks. is there any plan to introduce this as an official DynamoDB SDK for typescript? or is it gonna be side project?
If you guys not gonna invest heavily on this, i'd like to just stick on to own library since at least we can change it fast when we need something urgently (such as automatic batch split) but if this will be just an "experimental" project from aws, i know it's hard to expect that much of commitment. 
Otherwise, i can also consider just working on fork of this library so that we don't do same work twice you know.

**Comment by jeskew** [comment]
This project is going to continue to be developed and supported. At the moment, though, decorators are [a stage 2 proposal](https://github.com/tc39/proposals#stage-2) that TypeScript reserves the right to change to adapt to any evolution in the specification, and that may force breaking changes to the data mapper if the spec changes significantly. That said, the (type inference-based marshaller)[https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-auto-marshaller/], the (schema-based marshaller)[https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-data-marshaller/), and (DynamoDB expression composition and parsing library)[https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-expressions/] are published as separate NPM modules that can be used independently of the data mapper.

Re: batch operations specifically: I am working on handling batch operations in #19
