### ISSUE TITLE
ensureTableExists documentation is misleading

### ISSUE THREAD

**Issue by mbejda** [awslabs/dynamodb-data-mapper-js#152]
README states: 

> Like createTable, but only creates the table if it doesn't already exist:

`ensureTableExists` does not create a table. It only pauses execution until table status changes to active.

**Comment by jeskew** [comment]
`ensureTableExists` will pause execution until the table is active if it already exists; [if, however, DynamoDB returns a `ResourceNotFoundException`, `ensureTableExists` will call `createTable`](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-mapper/src/DataMapper.ts#L540).

**Comment by mbejda** [comment]
@jeskew 
 If that is the intended outcome I think there may be a bug.
Here is what I'm doing:

I start off with no tables in dynamodb local : 

<img width="640" alt="Screen Shot 2019-05-15 at 11 15 22 AM" src="https://user-images.githubusercontent.com/5429780/57787105-c62d2c80-7702-11e9-8741-225213e381b2.png">


I have a service with the following :  
```typescript
import * as DynamoDB from "aws-sdk/clients/dynamodb";
import ProjectModel from "../models/project";
import {DataMapper} from "@aws/dynamodb-data-mapper";

@Injectable()
export class DynamoDBService {
    mapper;
    constructor (public cognitoUtil: CognitoUtil) {
        console.log("DynamoDBService: constructor");
    }
    async init() {
        console.log('CREATE TABLE');
        this.mapper = new DataMapper({
            client: new DynamoDB({
                region: 'localhost',
                endpoint: 'http://localhost:8000'
            }),
            tableNamePrefix: 'dev_'
        });

        await this.mapper.ensureTableExists(ProjectModel,
            {
                readCapacityUnits: 5,
                writeCapacityUnits: 5,
                indexOptions: {
                    UserIdIndex: {
                        projection: 'all',
                        readCapacityUnits: 1,
                        type: 'global',
                        writeCapacityUnits: 1
                    }
                }
            });
    }
    async postProject(project){
        project.userId = this.cognitoUtil.getCognitoIdentity();
        try {
            const toSave = Object.assign(new ProjectModel, project);
            return await this.mapper.put(toSave);
        } catch(e){
            console.error(e);
            return e;
        }
    }
    writeLogEntry(a){

    }
    getLogEntries(a){

    }

}
```
on `init()` I'm calling `await this.mapper.ensureTableExists`. 
When I run it I should see a table created because it doesn't exist.
However, code fails with the following error:
```json
{"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Cannot do operations on a non-existent table"}
```
<img width="577" alt="Screen Shot 2019-05-15 at 11 17 04 AM" src="https://user-images.githubusercontent.com/5429780/57787312-20c68880-7703-11e9-9c3b-2c4339319bae.png">


Now, I do a sanity check to make sure everything else is working and rule out any other potential issues. I change `this.mapper.ensureTableExists` to `this.mapper.createTable`. 

```typescript

import {Stuff} from "../secure/useractivity/useractivity.component";
import * as AWS from "aws-sdk/global";
import * as DynamoDB from "aws-sdk/clients/dynamodb";
import ProjectModel from "../models/project";
import {DataMapper} from "@aws/dynamodb-data-mapper";

@Injectable()
export class DynamoDBService {
    mapper;
    constructor (public cognitoUtil: CognitoUtil) {
        console.log("DynamoDBService: constructor");
    }
    async init() {
        console.log('CREATE TABLE');
        this.mapper = new DataMapper({
            client: new DynamoDB({
                region: 'localhost',
                endpoint: 'http://localhost:8000'
            }),
            tableNamePrefix: 'dev_'
        });

        await this.mapper.createTable(ProjectModel,
            {
                readCapacityUnits: 5,
                writeCapacityUnits: 5,
                indexOptions: {
                    UserIdIndex: {
                        projection: 'all',
                        readCapacityUnits: 1,
                        type: 'global',
                        writeCapacityUnits: 1
                    }
                }
            });
    }
    async postProject(project){
        project.userId = this.cognitoUtil.getCognitoIdentity();
        try {
            const toSave = Object.assign(new ProjectModel, project);
            return await this.mapper.put(toSave);
        } catch(e){
            console.error(e);
            return e;
        }
    }
    writeLogEntry(a){

    }
    getLogEntries(a){

    }

}
```
And run the code. 
The table is created just fine.
<img width="184" alt="Screen Shot 2019-05-15 at 11 22 23 AM" src="https://user-images.githubusercontent.com/5429780/57787647-c37f0700-7703-11e9-9efc-658eafd23ef3.png">

So `ensureTableExists` did not create the table as the documentation states it should. Am I missing something here?

**Comment by mbejda** [comment]
@jeskew  I looked at the headers and noticed that `DescribeTable` is being called and I think that is what is making `ensureTableExists` fail.  
<img width="613" alt="Screen Shot 2019-05-15 at 11 31 38 AM" src="https://user-images.githubusercontent.com/5429780/57788381-068daa00-7705-11e9-892f-0d8857a2d0d2.png">

**Comment by jeskew** [comment]
The expected flow of `ensureTableExists` when the table does not exist is:
1. call `DescribeTable`
2. `DescribeTable` fails with a `ResourceNotFoundException`
3. call `CreateTable`.

What response do you see for the `DescribeTable` call?

**Comment by mbejda** [comment]
The response I'm seeing is `400` Bad Request.
```json
{"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Cannot do operations on a non-existent table"}
```
Digging deeper, I found out that the 400 bad request is not being caught by the try {} catch.
https://github.com/awslabs/dynamodb-data-mapper-js/blob/cbf79d940a82f6f16f1c2cc183ccd07fdb53e0fb/packages/dynamodb-data-mapper/src/DataMapper.ts#L539

I think that is why the table is not being created and I'm starting to think it *may* be an aws sdk configuration issue. I also see multiple requests being made to describe table.

**Comment by mbejda** [comment]
**Closing Issue....** After hours of debugging, there appears to be an issue with the aws-sdk. 

aws-sdk does not throw the proper exception for describeTable when invoked on frontend. 

Dynamodb-local returns the response
```
{"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Cannot do operations on a non-existent table"}
```
BUT,  the aws sdk ingests it and throws `NetworkingError: Network Failure` therfore the exception is not caught by the `try{}catch{}` mentioned earlier and the table is not created as expected.


```html
<html>
<head>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js">
    </script>

    <script>
        AWS.config.update({
            region: "us-east-1",
            endpoint: 'http://localhost:8000',
            accessKeyId: "...",
            secretAccessKey: "...",
            sslEnabled:     false,
            maxRetries:     1,
        });

        var docClient = new AWS.DynamoDB();

        function call() {

            var params = {
                TableName: 'dev_project'
            };
            try {
                const request = docClient.describeTable(params);
                request.
                on('success', function(response) {
                    console.log("Success!");
                }).
                on('error', function(response) {
                    console.log("Error! ",arguments);
                }).
                on('retry', function(response) {
                    console.log("retry!");
                }).
                on('httpError', function(response) {
                    console.log("httpError! ",arguments);
                }).
                on('complete', function(response) {
                    console.log("Always!", arguments);
                }).
                send();
            } catch(e){
                console.error('ERROR',e);
            }
        }
        call();

    </script>
</head>

<body>

</body>
</html>
```

<img width="1440" alt="Screen Shot 2019-05-15 at 10 05 55 PM" src="https://user-images.githubusercontent.com/5429780/57821200-a1b26e00-775d-11e9-9771-b57d6416598a.png">

**Comment by jeskew** [comment]
I forwarded your findings on to the DynamoDB local team to see if this is the expected behavior.
