### ISSUE TITLE
Creating and Dropping a Table

### ISSUE THREAD

**Issue by mikestead** [awslabs/dynamodb-data-mapper-js#21]
I've been trialling this new mapper out and very happy with how easy it was to get up and running.

One issue I hit was having to create tables in the more [verbose style](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#createTable-property). This felt like I was repeating many of the decorated values of the classes defining my model for this mapper.

Are there plans to support a table create and drop operation?

**Comment by jeskew** [comment]
Basic table creation and deletion does seem like something that this library should handle, particularly since the data mapper has abstractions for things relevant to table creation (like table name prefixes and time-to-live attributes).
