### ISSUE TITLE
Query pagination

### ISSUE THREAD

**Issue by mikestead** [awslabs/dynamodb-data-mapper-js#22]
I'm having a little difficulty understanding how to paginate and was hoping you could clarify.

Given the following code to pull 2 releases from a release group, I seem to be getting all releases in the group instead.

```JavaScript
const iterator = mapper.query(Release, { group }, { pageSize: 2 })
const releases = []
for await (const release of iterator) {
  releases.push(release)
}
return releases
```

I tried also using the deprecated `limit` option but no joy.

Perhaps this is to do with the async iterator, does it auto paginate under the hood? Any help  appreciated.

[Edit] I see https://github.com/awslabs/dynamodb-data-mapper-js/issues/7 talks a little about this, so would appear my assumption about auto pagination may be correct.

So setting a `pageSize` of 2 and then breaking from the loop after 2 iterations should mean only a single query hitting dynamo. I'll close the issue but please comment if this assumption is off the mark.

**Comment by jeskew** [comment]
The async iterator is paginating under the hood; if you break out of the loop in which releases are being pushed into an array after two iterations, then no further pages will be requested from DynamoDB.

**Comment by jeskew** [comment]
I would be open to making a breaking change to have `limit` cut off iteration after the specified count is reached, though that does differ from what the 'limit' parameter means to the underlying API call.

Alternatively, I put together a small library for working with async iterators that has a [`take`](https://jeskew.github.io/async-seq/index.html#take) function that would automate breaking out of the loop.

**Comment by LucasBadico** [comment]
@jeskew I already get the breack bit of the iterator, I'm just loosing the line of tooth on how to get back where I stop.

let's say
```js
const first10 = await repository.find(someQueryHere, {limit: 10, skip: 0})
const another 10 = await await repository.find(someQueryHere, { limit: 10, skip: 10 })
```
my repositiry is just using the mapper under the hood. (liked this expression rs)
```js
// for limit I could count the iterator itens
for await (const item of mapper.query(DomainClass, { id })) {
      this.bucket.push(item)
      if (this.bucket.lenght === limit) return this.bucket
}
```

But how I start the iterator on the 10 items ahead ?

**Comment by jan-wilhelm** [comment]
This is still an open question as it seems. Any news?

**Comment by LucasBadico** [comment]
I have doing some expirements but no good news.

**Comment by jeskew** [comment]
You can use a [`QueryPaginator`](https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-data-mapper/classes/querypaginator.html) to stop pagination at an arbitrary point and later resume it using the cursor returned by DynamoDB. Unfortunately, there is no way to skip a set number of items except by iterating over them -- Dynamo doesn't have any way to calculate how many values a query will return without executing it.

See [this comment](https://github.com/awslabs/dynamodb-data-mapper-js/issues/58#issuecomment-397831997) for an example of how to create and use a paginator and to get its query cursor (i.e., the `LastEvaluatedKey` property).
