### ISSUE TITLE
Only put when item doesn't already exist

### ISSUE THREAD

**Issue by mikestead** [awslabs/dynamodb-data-mapper-js#23]
Apologies for raising an issue again. I've been struggling for longer than I'd like to admit on this.

When doing a `put` I want to only succeed if an entry with the `id` doesn't already exist. Reading the [dynamodb docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html) it's done using `attribute_not_exists(id)`. 

I'm a little stuck in determining how to formulate that condition using `dynamodb-expressions`.

Here's my attempt.

```javascript
const release = new Release()
release.id = 'foo'
const condition = new FunctionExpression(
    'attribute_not_exists', 
    new AttributePath([{type: 'AttributeName', name: 'id'}]),
)
await mapper.put(release, { condition }) 
```

This gives me a `ValidationException: ExpressionAttributeValues must not be empty` error but I can't for the life of me work out how to solve this (maybe I need `new AttributeValue({ S: release.id })` somewhere?), only that I'm guessing it's quite simple!

Thanks again for the work on this lib.

**Comment by jeskew** [comment]
This is an issue with the way condition expressions are being serialized. The fix included in #12 and #10 (only adding expression attribute names and values when a substitution has occurred) needs to be added to `put`.

**Comment by mikestead** [comment]
@jeskew thanks for the quick fix, working as expected now 👍

**Comment by dragosbulugean** [comment]
@mikestead what is the expression that works? I don't seem to be able to make it work :(. like you I spent more than I'm able to admit

**Comment by mikestead** [comment]
@dragosbulugean I'm using the code in the original question, and `v0.3.2` of the lib currently (it's up to `v0.4.0` now).

I look at the `Error.code` for `ConditionalCheckFailedException`

```JavaScript
try {
    await mapper.put(release, { condition })
} catch (e) {
    if (e.code === 'ConditionalCheckFailedException') {
      throw serviceError(409, 'Release exists', e)
    } else {
      throw e
    }
}
```

**Comment by livingmine** [comment]
CMIIW, it seems that based on the current version of dynamodb-data-mapper-js as the time of this writing (v0.4.0), to achieve the same functionality as the OP described, the syntax is slightly different.
`mapper.put(release, {condition}` should be instead `mapper.put({item: release, condition: condition})` for it to be working as expected. From the source code at DataMapper.ts, it seems that on certain condition the `options` argument which is the way OP did to pass the `condition` is overriden with `itemOrParameters` which in this case equals to `release` in which does not contain any condition expression. Hence the solution for me to get it working is to pass `item` and `condition` together as the first parameter and leaving the second parameter blank. Is this intended?
