### ISSUE TITLE
Types not autodetected with serverless-plugin-typescript

### ISSUE THREAD

**Issue by kennu** [awslabs/dynamodb-data-mapper-js#25]
I noticed that when using https://github.com/graphcool/serverless-plugin-typescript to deploy TypeScript based Lambda applications, this doesn't work:

    @table(process.env.CONTACTS_TABLE!)
    class Contact {
      @hashKey()
      userId: string
      @rangeKey()
      contactId: string
    }

The type of all attributes becomes 'Any', which causes e.g. DataMapper.get() to throw a *ValidationException: The provided key element does not match the schema*, because it can't figure out how to marshal the key.

My workaround is to manually specify the types:

    @table(process.env.CONTACTS_TABLE!)
    class Contact {
      @hashKey({ type: 'String' })
      userId: string
      @rangeKey({ type: 'String' })
      contactId: string
    }

Is there some option `serverless-plugin-typescript` could use to keep the type metadata around when building the Lambda code?

**Comment by kennu** [comment]
Btw, it took a long time to debug this, because DataMapper silently accepts the 'Any' type and doesn't warn anything about lack of proper Key schema. I wish there would be some debug output to help with mystery situations like this.

**Comment by jeskew** [comment]
Hi @kennu,

I can add a check to the `hashKey` and `rangeKey` functions that will throw an error if they are used to decorate a property that is not a suitable key type.

Is `emitDecoratorMetadata` enabled in the affected project's tsconfig? TypeScript types are not available at runtime without this compiler option enabled.

**Comment by kennu** [comment]
Thanks! Adding `emitDecoratorMetadata` to tsconfig.json helped. It would be very helpful if the error message from hashKey/rangeKey would advise to add it there.
