### ISSUE TITLE
DataMapper batchGet method example

### ISSUE THREAD

**Issue by dianascarlett** [awslabs/dynamodb-data-mapper-js#31]
Hello, sorry for opening an issue but I just need to know how to use the `batchGet` in the Data Mapper.

I created the model classes using DataMapper Annotations and passed new instances of those classes to the `batchGet` method in a `for await` but it returns null. 

These classes work fine for other methods such as get, put etc.

Example

```
const gets = [new Class1(), new Class2()];

for await (const item of mapper.batchGet(gets)) {
                console.log(item)
}
```

Thank you.

**Comment by jeskew** [comment]
Hi @dianascarlett,

I can add examples for the batch methods to the readme file; it would probably be helpful to have examples for all methods.

The issue you're running into is that `batchGet` will only return results for items that exist in the table; no result is returned if the key does not exist. The first line would look something like the following (vary based on the key properties used for `Class1` and `Class2`):

```typescript
const gets = [
    Object.assign(new Class1, {keyProperty: 'keyValue'}),
    Object.assign(new Class2, {keyProperty: 'keyValue'}),
];
```

**Comment by VeryAlex02** [comment]
Hi!

I'm not sure either on how to use your library when I use annotations:

```
@table('Rule')
export class Rule {

    @hashKey()
    private sourceID : string;

    @rangeKey({defaultProvider: () => uuid.v4()})
    private ID : String;
...
}
```
```
public queryRulesBySourceID(sourceID : string) : AsyncIterableIterator<Rule> {
        const keyCondition = {
            sourceID: sourceID
        };
        return mapper.query(Rule, keyCondition);
    }
```

When I run it I get:
```
2018-03-10T00:32:04.509Z	744846f1-23fa-11e8-b2c1-7db081c5c204	(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert object to primitive value
```

So, it seems that it got some results but it wasn't able to transform them. 

Any idea what might be happening?
