### ISSUE TITLE
KeySchema.d.ts (10,30): Cannot find name 'KeyType'

### ISSUE THREAD

**Issue by kennu** [awslabs/dynamodb-data-mapper-js#33]
When deploying using Serverless Framework 1.26.1 and serverless-plugin-typescript 1.1.5, I get this error when using dynamodb-data-mapper 0.4.0 and dynamodb-data-mapper-annotations 0.4.0:

    node_modules/@aws/dynamodb-data-marshaller/build/KeySchema.d.ts (10,30): Cannot find name 'KeyType'.

At runtime, in the Lambda function, I see another error when executing:

    module initialization error: Error
    at /var/task/node_modules/@aws/dynamodb-data-mapper-annotations/build/attribute.js:70:19
    at DecorateProperty (/var/task/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (/var/task/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/var/task/lib/tables.js:4:92)
    at /var/task/lib/tables.js:17:5
    at Object.<anonymous> (/var/task/lib/tables.js:27:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

When I downgrade to dynamodb-data-mapper 0.3.2 and dynamodb-data-mapper-annotations 0.3.2, everything works fine.

**Comment by jeskew** [comment]
Looks like the `KeySchema.ts` file is missing an import, but `KeyType` is defined as an alias for `string` in TypeScript's DOM typings, which masked the error in the module's tests.

**Comment by jeskew** [comment]
The error thrown on `node_modules/@aws/dynamodb-data-mapper-annotations/build/attribute.js:70:19` is meant to be an early indication that some typing information is missing. (The TS source for this error can be found [here](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-mapper-annotations/src/attribute.ts#L90), but the error message is getting swallowed.) Is the `emitDecoratorMetadata` compiler option enabled in the application's tsconfig?

**Comment by danieladams456** [comment]
I'm seeing the same thing, and I do have `"emitDecoratorMetadata": true`.

**Comment by jeskew** [comment]
@danieladams456 You may be applying a key decorator to a property of an ambiguous or the wrong type. Can you share a snippet?

**Comment by danieladams456** [comment]
### tsconfig.json
(I had to do [this fix](https://github.com/apollographql/graphql-subscriptions/issues/83) for `node_modules/@aws/dynamodb-data-mapper/build/DataMapper.d.ts(32,81): error TS2304: Cannot find name 'AsyncIterableIterator'.`)

```json
{
  // see https://github.com/Microsoft/TypeScript-Node-Starter/blob/master/tsconfig.json
  "compilerOptions": {
    // output levels
    "target": "es6",
    "module": "commonjs",
    "lib": [
      "es6",
      "esnext.asynciterable"
    ],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    // files and paths, enable sourceMap later if needed
    "sourceMap": false,
    "outDir": "dist",
    "rootDir": "src",
    // enable all strict type checking
    "strict": true,
    // additional checks
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    // type declaration files to be included in compilation
    "types": [
      "node"
    ]
  },
  "include": [
    "src/**/*"
  ]
}
```
### index.ts
```typescript
import { DataMapper } from '@aws/dynamodb-data-mapper';
import {
  attribute,
  hashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';
import DynamoDB = require('aws-sdk/clients/dynamodb');

// set proxy
const tunnel: any = require('tunnel-agent');
const proxyAgent = tunnel.httpsOverHttp({
  proxy: {
    host: 'localhost',
    port: 3128,
  },
});

@table('daniel-dynamodbmapper-java')
class NumericItem {
  @hashKey()
  public number: number = 0;

  @attribute()
  public word: string = '';
}

// how to make this a builder/immutable/one statement?
const toPut = new NumericItem();
toPut.number = 11;
toPut.word = 'eleven';

const client = new DynamoDB({ region: 'us-east-1', httpOptions: { agent: proxyAgent } });
const mapper = new DataMapper({ client });

mapper.put(toPut)
  .then(persisted => console.log('persisted:', persisted))
  // arrow function references lexical scope
  .then(() => mapper.delete(toPut))
  .then(deleted => console.log('deleted:', deleted))
  .catch(console.error);
```
Thank-you for your help!

**Comment by danieladams456** [comment]
I am not having this issue any more with dynamodb-data-mapper 0.5.0 and dynamodb-data-mapper-annotations 0.5.0.  You can probably close it as I would guess it fixes @kennu's problem as well.

**Comment by kennu** [comment]
Yeah the problem was fixed also for me, thanks.
