### ISSUE TITLE
Detecting ItemNotFoundException

### ISSUE THREAD

**Issue by kennu** [awslabs/dynamodb-data-mapper-js#34]
It's a little unclear to me how to detect that dynamo.get() is throwing an ItemNotFoundException. In my code I'm trying this:

    try {
      const response = await dynamo.get(param)
      return response
    } catch (err) {
      if (err instanceof ItemNotFoundException) {
        throw new Error('[404] Not Found')
      } else {
        throw err
      }
    }

Here instanceof never detects that the thrown error is ItemNotFoundException (returns false). Is there some other way to do it, or am I missing something in TypeScript options?

As an alternative, perhaps ItemNotFoundException should include a .code attribute like AWS SDK errors do. Then you could easily check if (err.code === 'ItemNotFoundException') to handle the error.

PS. This is under Serverless Framework + serverless-plugin-typescript.

**Comment by jeskew** [comment]
I put up #36 to set the name property of `ItemNotFoundException`s to `'ItemNotFoundException'` -- this should give those errors a stable identifier and also show up when the error is logged.

**Comment by donaldpipowitch** [comment]
It would probably work with this change:

```diff
export class ItemNotFoundException extends Error {
    readonly name = 'ItemNotFoundException';

    constructor(
        public readonly itemSought: GetItemInput,
        message: string = defaultErrorMessage(itemSought)
    ) {
        super(message);
+       Object.setPrototypeOf(this, ItemNotFoundException.prototype);
    }
}
```

This is the recommended way mentioned [here](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work).
