### ISSUE TITLE
How to handle nullable attributes?

### ISSUE THREAD

**Issue by joostfarla** [awslabs/dynamodb-data-mapper-js#35]
I'm having a DynamoDB property which can have value type `String` or `Null`. My TypeScript mapping looks like this:

```js
@table('table_name')
class MyDomainClass {
    @hashKey()
    id: string;

    @attribute()
    requiredProperty: string;

    @attribute()
    optionalProperty: string | null;
}
```

When I perform a query using `@aws/dynamodb-data-mapper`, the result is:

```json
{
  "id": "foo",
  "requiredProperty": "bar",
  "optionalProperty": ""
}
```

I would expect `optionalProperty` to have value `null`. The corresponding document looks like:

```json
{
  "id": { "N": 1},
  "requiredProperty": { "S": "Foo" },
  "optionalProperty": { "NULL": true }
}
```

**Comment by jeskew** [comment]
For strings, sets, and buffers, `{NULL: true}` is treated as an emptiness sigil, as DynamoDB does not allow zero-length values for those types. (See https://github.com/aws/aws-sdk-js/issues/833 for more discussion.) Since DynamoDB allows attributes to be omitted from records, `undefined` is used when no value is present.

You can use an attribute with type of `'Custom'` to capture the use case you describe.

**Comment by joostfarla** [comment]
@jeskew Thanks for the clarification!

I've now solved it by using a custom type. Example:

```js
const NullableString: CustomType<string> = {
  type: 'Custom',
  marshall(input) {
    if (input === '') {
      return { NULL: true };
    }

    return { S: input };
  },
  unmarshall(persistedValue) {
    if (persistedValue.NULL === true) {
      return null;
    }

    return persistedValue.S;
  }
};

@table('table_name')
class MyDomainClass {
    @hashKey()
    id: string;

    @attribute()
    requiredProperty: string;

    @attribute({ memberType: NullableString })
    optionalProperty: any;
}
```

This works perfectly! The only thing is that I had to specify type `any` instead of `string | null`. Is that desired behaviour?

**Comment by jeskew** [comment]
The type of `optionalProperty` is still being inferred from TypeScript's decorator metadata. The `memberType` schema property is only used by lists and maps (where it describes the elements contained in the list or map), so the decorator is still trying to figure out what `type` property to apply. (`any` directs the marshaller to detect the type at runtime using the [auto marshaller](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-auto-marshaller/src/Marshaller.ts#L104), which happens to match the behavior of the `NullableString` type you've defined.)

I think what you want would be:

```typescript
class MyDomainClass {
    // ...
    @attribute(NullableString)
    optionalProperty: string|null;
}
```

**Comment by joostfarla** [comment]
Ah that makes sense! Thanks @jeskew!!
