### ISSUE TITLE
startKey property of scan method automatically set the default value 

### ISSUE THREAD

**Issue by code-atom** [awslabs/dynamodb-data-mapper-js#39]
Hi, I am tried to implement the paging the application and while doing  i am setting the last accessed id in startkey property of scanOption

**var option: ScanOptions = {
    filter: notEqualExpression,
    projection: projection
  };
  if (startKey) {
    option.startKey = { id : startKey };
  }
  var query = mapper.scan(User, option);**

while doing this I am getting this error **"The provided starting key is invalid: The provided key element does not match the schema"**

Here my model definition:
@table("Users")
export class User {
  @hashKey() id: string;

  @attribute() email: string;

  @attribute() firstName: string;

  @attribute() lastName?: string;

  @attribute() photoUrl?: string;

  @attribute() heading?: string;

  @attribute() biography?: string;

  @attribute() phone?: string;

  @attribute({ defaultProvider: () => new Date() })
  createdDate: Date;

  @attribute({ defaultProvider: () => true })
  active: boolean;

  @attribute({ memberType: "String" })
  deviceTokens?: JSONSet<string>;

  @attribute() paypalEmail?: string;

  @attribute({ defaultProvider: () => false })
  approved: boolean;

  @attribute({defaultProvider: ()=> 'basic'})
  provider: string;
}

After the debugging this issue, i found that ExclusiveStartKey expression also contain the default value of attributes in which defaultProvider is provided.

**Comment by jeskew** [comment]
Can you post the response you get to performing a [`DescribeTable` operation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeTable.html) on the `Users` table? The error reported is being returned by DynamoDB and indicates that the table schema does not match the schema defined in code.
