### ISSUE TITLE
Example for updateItem with Increment

### ISSUE THREAD

**Issue by winjer** [awslabs/dynamodb-data-mapper-js#41]
Hi,

I cant figure out how to get e.g.:
`
    "UpdateExpression": "set Replies = Replies + :num",
`
in a call to UpdateItem via the `update` method. Can you give me a clue?

**Comment by jeskew** [comment]
You would need to drop down to the low-level client to execute a custom expression; the `update` takes an object and converts its current state to an update expression.

The [`@aws/dynamodb-expressions` package](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-expressions/) provides composable expression objects that serialize to DynamoDB expression strings that can be used with the regular AWS SDK. (The data mapper uses this package internally for queries, scans, and updates, and operation conditions.) Try the following:

```javascript
import {
    AttributePath,
    ExpressionAttributes,
    MathematicalExpression,
    UpdateExpression,
} from '@aws/dynamodb-expressions';

const attributes = new ExpressionAttributes;
const updateExpression = new UpdateExpression;
updateExpression.set('Replies', new MathematicalExpression(new AttributePath('Replies'), '+', 4);

ddbClient.updateItem({
    Key: {KeyProp: {S: 'key'}},
    TableName: 'tableName',
    UpdateExpression: updateExpression.serialize(attributes),
    ExpressionAttributeNames: attributes.names,
    ExpressionAttributeValues: attributes.values,
});
```

(Also runnable [on runkit](https://runkit.com/jeskew/runkit-npm-aws-dynamodb-expressions-set-example).)

**Comment by winjer** [comment]
This works a treat, thanks so much for the help, it is really appreciated ;)

**Comment by LucasBadico** [comment]
Guys, can you help me with a little thing, why we are using this new keyword without a  `()` after the constructor. First time seeing this...

**Comment by jeskew** [comment]
@LucasBadico - `new ExpressionAttributes` and `new ExpressionAttributes()` are equivalent; it's just a matter of personal preference.
