### ISSUE TITLE
GSI pagination issues on version 0.4.1

### ISSUE THREAD

**Issue by buccolo** [awslabs/dynamodb-data-mapper-js#45]
Hey o/

First of all, we've been using `dynamodb-data-mapper` for a few months and it has been great, so thanks for the project!

One thing I've noticed is that GSI pagination is broken for me since 0.4.1.

Here's my table structure:

- Table Name: offers
- Hash: `merchant_id`
- Range: `object_id`
- GSI
  - IndexName: status_merchant_id
  - Hash: `status`
  - Range: `merchant_id`

The Exclusive Start Key of a GSI pagination usually looks like this:
```
{ 
  merchant_id: '1234,
  object_id: '456',
  status: 'INACTIVE' 
}
``` 

I'm getting this error message `The provided starting key is invalid` now when doing GSI queries.

I believe the error could be related to this PR:
https://github.com/awslabs/dynamodb-data-mapper-js/pull/40/files#diff-5308a7ee95cbc7142d35cd94cd31c718

I'm not familiar with the inner workings of the project, but it seems that only the table keys will be serialized, but not the keys from my GSI. Because `status` was not serialized, that error is happening.

Does that make sense?

**Comment by jeskew** [comment]
That does make sense, and it looks like the same issue would be present [when performing a scan](https://github.com/awslabs/dynamodb-data-mapper-js/blob/v0.4.1/packages/dynamodb-data-mapper/src/DataMapper.ts#L1088). `marshallKey` takes an optional `indexName` parameter, so this should be a simple fix.
