### ISSUE TITLE
Error installing package @aws/dynamodb-data-mapper

### ISSUE THREAD

**Issue by elescrim** [awslabs/dynamodb-data-mapper-js#5]
c:\Code\>npm i @aws/dynamodb-data-mapper --save-dev
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws/dynamodb-auto-marshaller@^0
.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@aws/dynamodb-expressions
'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:

---

1 verbose cli   'i',
1 verbose cli   '@aws/dynamodb-data-mapper',
1 verbose cli   '--save-dev' ]
2 info using npm@5.5.1
3 info using node@v6.10.1
4 verbose npm-session 00f8b4978f16d8bc
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@aws%2fdynamodb-data-mapper 1617ms (from cache)
8 silly pacote tag manifest for @aws/dynamodb-data-mapper@latest fetched in 1646ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @aws/dynamodb-data-mapper@0.1.0 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/@aws%2fdynamodb-expressions 320ms (from cache)
15 silly pacote range manifest for @aws/dynamodb-expressions@^0.1.0 fetched in 323ms
16 silly resolveWithNewModule @aws/dynamodb-expressions@0.1.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@aws%2fdynamodb-data-marshaller 572ms (from cache)
18 silly pacote range manifest for @aws/dynamodb-data-marshaller@^0.1.0 fetched in 575ms
19 silly resolveWithNewModule @aws/dynamodb-data-marshaller@0.1.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/@aws%2fdynamodb-auto-marshaller 403ms (from cache)
21 silly pacote range manifest for @aws/dynamodb-auto-marshaller@^0.1.0 fetched in 405ms
22 silly resolveWithNewModule @aws/dynamodb-auto-marshaller@0.1.0 checking installable status
23 silly registry:manifest no matching version for @aws/dynamodb-auto-marshaller@^0.0.0 in the cache. Forcing revalidation
24 http fetch GET 304 https://registry.npmjs.org/@aws%2fdynamodb-auto-marshaller 341ms (from cache)
25 silly fetchPackageMetaData error for @aws/dynamodb-auto-marshaller@^0.0.0 No matching version found for @aws/dynamodb-auto-marshaller@^0.0.0
26 verbose type range
27 verbose stack @aws/dynamodb-auto-marshaller: No matching version found for @aws/dynamodb-auto-marshaller@^0.0.0

**Comment by jeskew** [comment]
Thanks for the feedback; I'm still learning the ropes of lerna. This should be fixed in version 0.1.1
