### ISSUE TITLE
UpdateExpression with DataMapper.update

### ISSUE THREAD

**Issue by mafrosis** [awslabs/dynamodb-data-mapper-js#50]
Is it possible to use an `UpdateExpression` with the [DataMapper.update](https://github.com/awslabs/dynamodb-data-mapper-js/tree/master/packages/dynamodb-data-mapper#update) method?

I think the docs around advanced usage could use a little more detail and examples :) I am happy to pull request some of this, but I haven't been able to get much of it working myself!

**Comment by jeskew** [comment]
A PR with this change is up at #53 

For docs, PRs adding to the JSDoc blocks or to the package READMEs are always welcome. Anything in particular that you haven’t been able to get working?

**Comment by jeskew** [comment]
This feature was included in v0.5.0
