### ISSUE TITLE
DataMapper batchPut method example

### ISSUE THREAD

**Issue by jpmonette** [awslabs/dynamodb-data-mapper-js#51]
Trying to get my head around how to successfully use this to batch insert records, but keep ending with error messages - I assume what I input in the `batchPut` function is in the wrong format.

Would it be possible to provide some example?

Thanks

**Comment by jeskew** [comment]
The simplest way to use `batchPut` is to just give the method an array of the objects you want to write. You can also provide an iterable (or an async iterable) if you want to lazily create the objects to write.

Right now, the only "examples" are the [test cases](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-mapper/src/DataMapper.spec.ts#L522), which run through the different scenarios supported but are not optimized for reading. I could add examples to the root readme.
