### ISSUE TITLE
initialise DataMapper without import

### ISSUE THREAD

**Issue by gnovy** [awslabs/dynamodb-data-mapper-js#56]
How do I initialise the DataMapper class without using the import statements for DataMapper and DynamoDB?

**Comment by jeskew** [comment]
The `@aws/dynamodb-data-mapper` package is published as CommonJS module, so you would need to write a small wrapper script if you wanted to expose it as a global object.

Would it help if the package were also published as an ES module? You would still need to use an `import` statement, but you could use it in a browser without bundling.

**Comment by gnovy** [comment]
Ah, got it. I should do the following, 
_const DataMapper = require("@aws/dynamodb-data-mapper").DataMapper_
I'm using it in nodejs lambda without typescript.
Very useful package! Thanks!
