### ISSUE TITLE
Is BeginsWith ConditionExpression supported?

### ISSUE THREAD

**Issue by ahimik** [awslabs/dynamodb-data-mapper-js#57]
Hi there!
I couldn't find BeginsWithExpressionPredicate among the others.
Is there any reason not to support it?
How can I query by a hashKey in a pair with a sortKey using begins_with sort key condition expression?
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html

Thanks in advance!

Really nice wrapper BTW! I enjoy using it.

**Comment by jeskew** [comment]
Hi @ahimik,

I initially avoided making expression predicates for functions, as a function doesn't necessarily need to use a path as the first argument. While that's technically true, all functions supported by DynamoDB today take an attribute path as their first argument, so I could revisit that decision.

To perform that query with version 0.5.0, you would do something like:

```typescript
mapper.query(
    MyClass, 
    {type: 'And', conditions: [
        {type: 'Equals', subject: 'hashKey', object: hashValue},
        new FunctionExpression('begins_with', new AttributePath('sortKey'), sortKeyPrefix)
    }
);
```

It's not quite as ergonomic as performing a query without the second condition clause (`mapper.query(MyClass, {hashKey: hashValue})`), but it should accomplish what you want.

**Comment by ahimik** [comment]
Hi @jeskew,

Thank you for such a quick reply! I'll try this as soon as possible.

I am not sure that this is a good place to ask it but there is one more question I am really worried about.
Since we've decided to follow dynamodb bestpractices and chosen single-table design where we represented our nested items as a top-level nodes coupled by a haskey. I am wondering what is the best practices for quering and mapping single table to a multiple js classes using this mapper. Mapping all items to the same class with all possible fields looks bad to me so I've decided to map the same table to a different classes and query them separately by hashkey+sorkey but it seems like both approaches have their pros and cons.
 
I appriciate if you can suggest something here or point to some documentation.
Thank you!

**Comment by jeskew** [comment]
Right now at least, the mapper expects tables to contain a single type. 

How are the different types distinguished in the single table design used? Is there a discriminator field (like [in this example](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/inheritance-mapping.html#single-collection-inheritance)) or is a partition key prefix used (like in the adjacency list pattern described [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html))?

**Comment by ahimik** [comment]
Yes, there is a discriminator field. I was looking for exactly similar solution based on inheritance but I think it's not supported yet?
The table's structure is something like:
HashKey     |     SortKey    |      Player name    |   Player age    |     Game name   |    More attributes...
_________________________________________________________________________________________________________
  "123"        |     "player"    |        "Mister X"     |       "34"          |                            |
  "123"        |    "game-1"  |                              |                        |       "Dota 2"       |
  "123"        |    "game-2"  |                              |                        |       "WoW"        |
_________________________________________________________________________________________________________

And as a result I have always to return a player with the complete list of games in the following structure:
"player" {
   "name": "Mister X",
   "age": "34",
   "games": [ {"Dota 2",  "WoW"} ]
}
therefor I have to query all the records by a given hashKey and then sort and convert them into required structure. The discriminator field here is a prefix of the sort key but it can be stored as an additional attribute as well.

For now I came up with the following solution:

1. I've created Player and Game classes and map them to the same table.
2. I've created mixin class "Record" which extends both Player and Game classes.
3. I provide mixin "Record" class as a value constructor to a mapper when querying by a given hashKey
and get all the records of a particular player.
4. Then I sort and combine those records by simply assigning mixin class to a conrete class based on a record type without having to explicitly convert them.
5. Build response object.

Does it make sense?
Thank you!
