### ISSUE TITLE
Query/Scan limit is ignored

### ISSUE THREAD

**Issue by kennu** [awslabs/dynamodb-data-mapper-js#6]
I can specify the limit parameter to query() and scan(), but because the result iterator keeps reading on using lastEvaluatedKey, all result rows are always returned and limit only becomes a batch size parameter.

Perhaps the iterator should manually check that if limit is reached, it stops yielding results?

**Comment by jeskew** [comment]
That's a good point. Right now, that parameter is meant to control batch size, and it uses the same name as the underlying DynamoDB API parameter. That name is misleading when the result pages are being flatmapped into an item iterator.

I could add a separate `batchSize` parameter that would do what `limit` is doing now and change limit to act as a bound on the returned iterator, as you suggested.

**Comment by puzzloholic** [comment]
Hi @jeskew ,

Is there a way you could enable limit as separate purpose for pageSize?

This is my use case:
I want to text search on a table (around 12k items) by using scan, and I want to make batchSize rather big (around 1k) to avoid Lambda Function execution time limit.
But I just want to retrieve first 100 items, not all of them, to suggest user refine their search if the result is too big.
If I set `pageSize` parameter to 100, I will have Time Limit Exceeded Error on Lambda, but if I set it to 1000, the loop will continue the scan after 100 items found.

Is there a way to achieve this using the current API?

**Comment by jeskew** [comment]
@puzzloholic You can set `pageSize` and `limit` separately. 

```typescript
mapper.scan(Ctor, { 
    pageSize: 1, 
    limit: 10
});
``` 
would request pages with 1 element and cease iteration after encountering 10 items.

**Comment by puzzloholic** [comment]
@jeskew I have already play with that two parameters.

This is result I got:
- pageSize: 100, limit: 100, will do scan process every 100 items and stop at 100 items found
- pageSize: 1000, limit: 1000, will do scan process every 1000 items and not stopped until scan is finish (maybe because no scan yield more than 1000 result)
- pageSize: 1000, limit: 100, will do scan process every 100 items and stop at 100 items found
- pageSize: 100, limit: 1000, will do scan process every 100 items and not stopped until scan is finish

**Comment by jeskew** [comment]
The iterator will keep going until all results are exhausted or `limit` is reached. Do you want to instead process each page of results as it is received? That can be done by detaching the [paginator](https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-data-mapper/classes/scanpaginator.html):

```typescript
const paginator = mapper.scan(Ctor, {pageSize: 100}).pages();
for await (const page of paginator) {
    // do something with a page of results. 
    // Each page will contain a maximum of 100 records.
}
```

See https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-data-mapper/classes/scaniterator.html#pages for documentation of this feature.
