### ISSUE TITLE
Global Secondary Index

### ISSUE THREAD

**Issue by newtack** [awslabs/dynamodb-data-mapper-js#60]
1. Can I use this mapper to create DynamoDB tables?
2. If so, how do I create global secondary indexes and specify rcu/wcu and other parameters?

**Comment by acheronfail** [comment]
For those wanting to know how to create Global Secondary Indexes (GSI) with this lib, you'll also need to specify which indexes your attributes are a part of when defining your schema.

Best explained with an example:
```js
@table(process.env.DYNAMO_ITEMS_TABLE_NAME!)
export class Item {
  @hashKey()
  itemId: string;    // <-- this is your normal hash key (not part of GSI)

  @rangeKey({
    // This is the HashKey for the GSI
    indexKeyConfigurations: {
      ItemIdIndex: 'HASH'
    }
  })
  displayName: string;

  @attribute({
    // This is the RangeKey for your GSI
    indexKeyConfigurations: {
      ItemIdIndex: 'RANGE'
    }
  })
  foo: string;

  @attribute()
  bar: string;
}
```

That way, `@aws/dynamo-data-mapper` knows which attributes are used in the GSI.

**Comment by acheronfail** [comment]
In my experience you need to do both: specify them in the `createTable` code, and ensure that what you specified there matches the attributes in your item class (if you read though the source of this repo you'll see how it checks for both).

**Comment by jeskew** [comment]
@jeffreyyoung What @acheronfail says above is correct; you need to supply information in both locations.

The mapper needs to know what fields represent a hash or range key when executing a `query` or `scan` operation. This is captured by the `indexKeyConfigurations` property of the object provided to the `@attribute` annotation on class properties.

Additional information about each index is required to create a table or add an index (the provisioned capacity, the index type, the property projection, etc) but is not used when executing data operations on the table. This is what must be supplied to `createTable`.

**Comment by jeffreyyoung** [comment]
@jeskew sounds good. thank you!
