### ISSUE TITLE
Adjacency List Design Pattern

### ISSUE THREAD

**Issue by newtack** [awslabs/dynamodb-data-mapper-js#62]
Per the DynamoDB docs one should only use a single table and use things like "Adjacency List Design Pattern" to implement this, see links below.

Ideally I would like to have to multiple domain objects that all point to the same table and handle the id automatically (e.g. order-15 for order id 15, and customer-123 for customer id 123).

How would I implement this with this library? 

Refs:
[](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-modeling-nosql-B.html?shortFooter=true)
 https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html#bp-adjacency-lists

**Comment by newtack** [comment]
Here is an example for it:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-modeling-nosql-B.html?shortFooter=true

**Comment by jeskew** [comment]
There's no built-in support for adjacency list tables, but I can leave this open as a feature request for adding such support.

You can define a property as having a [custom attribute type](https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-data-marshaller/interfaces/customtype.html), which would allow you to specify a custom property marshaller and unmarshaller. For an adjacency list, the marshaller could just be a function that prepends a type identifier to the item, and the unmarshaller could be a function that strips it. The main drawback to this approach is that `query` and `scan` wouldn't automatically inject a `begins_with` function to filter out entries belonging to another domain item.

Alternatively, you could model the adjacency list itself and then stick another layer on top of it. This would let you abstract away key prefix injections and conditions into a repository class.

**Comment by jeskew** [comment]
If you were using the table described [in the DynamoDB guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html#bp-adjacency-lists), you would do something like the following:

```typescript
class Invoice {
    @attribute({
        type: 'Custom',
        attributeType: 'S',
        marshall: str => ({S: `Invoice-${str}`}),
        unmarshall: persisted => persisted.S!.replace(/^Invoice-/, '')
    })
    partitionKey: string;
}

class Bill {
    @attribute({
        type: 'Custom',
        attributeType: 'S',
        marshall: str => ({S: `Bill-${str}`}),
        unmarshall: persisted => persisted.S!.replace(/^Bill-/, '')
    })
    partitionKey: string;
}
```

**Comment by newtack** [comment]
Thanks!
