### ISSUE TITLE
Sparse Column

### ISSUE THREAD

**Issue by newtack** [awslabs/dynamodb-data-mapper-js#63]
Per the DynamoDB docs one pattern is a sparse index, which relies on the fact that an attribute is not there at all at times.

In the example (see link below), how can I specify that if the boolean field is true, specify an attribute, otherwise not?

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general-sparse-indexes.html

**Comment by jeskew** [comment]
If a column isn't present in a record, it won't be unmarshalled. It's up to you how this should be represented in a mapped class, but I would recommend explicitly marking the property as optional in your type definition:

```typescript
class MappedClass {
    @attribute()
    sparseColumn?: string;
}
```
