### ISSUE TITLE
Exclude tsconfig.json from build output

### ISSUE THREAD

**Issue by newtack** [awslabs/dynamodb-data-mapper-js#70]
I get the following in VSCode:
No inputs were found in config file '/Users/ralf/code/pitta/ts/node_modules/@aws/dynamodb-auto-marshaller/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["./build"]'.

This is the same for all of the packages. The build has a tsconfig.json in the output but no Typescript files. Can you please exclude tsconfig.json from the individual packages?

**Comment by jeskew** [comment]
#71 has a fix for this. In the meantime, you can work around any build errors by adding "node_modules" to the excluded paths array in the application's `tsconfig.json` file.
