### ISSUE TITLE
A little question on update method.

### ISSUE THREAD

**Issue by LucasBadico** [awslabs/dynamodb-data-mapper-js#74]
The update method will overhide the data if I just send a partial of this data?
my data has a `id` and a `name` already.
```js
mapper.update({
id: 'someid',
list: [a list]
})
```
If do this I will be erasing the name?

**Comment by jeskew** [comment]
By default, the `name` property would be removed by executing that update, but this behavior is configurable via the [`onMissing` option](https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-data-mapper/interfaces/updateoptions.html#onmissing).

If you instead use `mapper.update(item, {onMissing: 'skip'})`, then only the non-key properties for which a value is provided in `item` will be updated. If the `onMissing` option is instead set to `'remove'` or not provided, then any non-key property described in the schema for which no value is provided will be removed.
