### ISSUE TITLE
Q: Annotated Model - Import in node.js function - Annotation lost error (No object property was found)

### ISSUE THREAD

**Issue by nea** [awslabs/dynamodb-data-mapper-js#75]
Hi

I am really digging the concept and would like to apply the given SDK here. The issue I am facing is the following:

I have a node application and would like to create model classes shared for different modules. These models should define their own ```DynamoDbTable``` and ```DynamoDbSchema```. Everything is JavaScript es2015.

Now, if I define the classes and export them I can reuse them but the symbols are not created/available. I would have to reset the configuration everywhere again where I would like to use the model class together with the datamapper to DynamoDB, otherwise it ends in

`Error: The provided item did not adhere to the DynamoDbDocument protocol. No object property was found at the "DynamoDbSchema" symbol`

I tried with Symbols in class, Object.defineProperties, as in the examples, but reusing the object only seems to grab an "interface" of it, without any content, even if I define e.g.
`
[DynamoDbTable]() {
        return 'posts';
}
`
in the class.

Is there any way to modularize this somehow without TypeScript or an upgrade NodeJS version? Only if I ```Object.defineProperties``` always again where I am using the model it does work.

Thanks in advance

**Comment by jeskew** [comment]
In theory, everything except type inference on annotated properties should work in vanilla JS.

Could you provide an example of what’s not working? I’m not sure I understand exactly what you mean by when you mention reusing the objects. (Do you mean creating a class hierarchy?)

**Comment by nea** [comment]
Hi @jeskew 

I am probably thinking wrong here, trying to create an example:

Running in a node.js environment, having a main index.js function being called, where the connection to DynamoDB is done, e.g.

`module.exports = function() {
    var client = new AWS.DynamoDB({
        apiVersion: "2012-08-10"
    });
    var mapper = new DataMapper.DataMapper({
        client
    });

    ....

    var item = Object.assign(new Item, {a: values[0], b: values[1]});
    mapper.put({item});

    ...
}`

Now, I have a shared folder with an item.js class, e.g.:
`class Item {
    constructor() {}
}

module.exports = Item;
`

Now, I tried to ```Object.defineProperties(Item.prototype,...``` directly in item.js, I tried to add the symbols in the class ```[DynamoDbTable]() { return 'item' }``` etc. but this information seems to be missing in the index.js when putting to DynamoDB leading to the error. 

I have to define the properties in the index.js otherwise it is not working. That is what I meant by reusing the model. 

I hope I was able to clear my probable thinking mistake ^^


Thanks a lot

**Comment by nea** [comment]
Hi

I tried the same with TypeScript now, created a Model, imported it ```import { Item} from "../shared/model/Item";``` and just did

```
const mapper = new DataMapper({
    client: new AWS.DynamoDB({ apiVersion: "2012-08-10" })
});

const item= new Item();
item.a= new Date();
item.b= 'User1';

mapper.put({item}).then(() => {
    console.log(item);
});
```

and get the same error.


Thanks

**Comment by nea** [comment]
Ok... my bad!

I had separate package.json in my different structures, I thought required because of dependencies but weren't, obviously. With a single package setup all seems to work now.

Will dig deeper why to get an explanation for myself, but this issue is solved for me.


Sorry for the inconvenience ^^'

**Comment by ajhool** [comment]
Hi nea, would you mind opening this issue again, I'm experiencing the same issue when using multiple packages.
