### ISSUE TITLE
About update Expressions

### ISSUE THREAD

**Issue by LucasBadico** [awslabs/dynamodb-data-mapper-js#77]
```
Update expressions allow the partial, in place update of a record in DynamoDB. The expression may have up to four clauses, one containing directives to set values in the record, one containing directives to remove attributes from the record, one containing directives to add values to a set, and the last containing directives to delete values from a set.
```

A set is  just a  ```Set```  or could also be a ```List``` ?

**Comment by jeskew** [comment]
The `ADD` and `DELETE` clauses in an update expression can only be used with sets, not with lists. To add an item to a list, you would need to use the `list_append` function in an update expression (DynamoDB has a guide on doing so [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.UpdatingListElements)); to remove an item, you would need to use the `REMOVE` clause and provide a path to a member of the list (guide available [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.REMOVE.RemovingListElements)).

**Comment by LucasBadico** [comment]
Thanks!
