### ISSUE TITLE
emitDecoratorMetadata tsconfig setting causes objects in property arrays to be empty

### ISSUE THREAD

**Issue by gambit66** [awslabs/dynamodb-data-mapper-js#84]
v0.6.1 (unable to use v0.7.0)

If I set emitDecoratorMetadata=true in tsconfig, then all my properties (attributes) that are arrays of objects will be persisted as an empty Javascript object in an array in the Dynamo DB table. Setting emitDecoratorMetadata=false resolves this issue.

```
    @table('business')
    export class Business {
        @autoGeneratedHashKey()
        id: string;

        @attribute()
        businessName: string;

        @attribute()
        primaryContact: Contact;

        @attribute({memberType: embed(Account)})
        accounts: Array<Account>;
    }
```

Accounts property persisted as:
`
"accounts":[{}]
`

**Comment by jeskew** [comment]
Could you post the `Account` class as well?

**Comment by gambit66** [comment]
Nothing special I'm afraid.

```
    export class Account {
        accountNumber: string;

        accountName: string;
    }
```

If I disable emitDecoratorMetadata then I have to use @autoGeneratedHashKey() instead of @hashKey() otherwise it throws an error saying that I need to enable emitDecoratorMetadata.

**Comment by jeskew** [comment]
The properties of `Account` that you would like to persist must be annotated, too. Type metadata is only available on decorated properties, so an empty schema would be created for the current `Account` class.
