### ISSUE TITLE
Avoid setters when hydrating domain objects

### ISSUE THREAD

**Issue by skylerrichter** [awslabs/dynamodb-data-mapper-js#88]
I am using a setter to hash passwords on my user class, which works great.

However it seems that the setter is being called when the domain object is hydrated from DynamoDB.

This means that passwords already stored in DynamoDB will be rehashed when the domain object is hydrated.

```
class User {

  checkPassword(password) {
    return bcrypt.compareSync(password, this.password);
  }

  get password() {
    return this._password;
  }

  set password(password) {
    this._password = bcrypt.hashSync(password, bcrypt.genSaltSync(10));
  }

}
```

When ever I try to use the `checkPassword` method after loading a domain object it returns false as the password has been rehashed.

What is the best way of dealing with this?

**Comment by jeskew** [comment]
I think in this case the best approach is to keep the `User` class's properties a straightforward representation of what is in the table. You can add methods for additional desired behaviors:

```typescript
class User {
  @attribute()
  password?: string;

  checkPassword(password: string): boolean {
    return bcrypt.compareSync(password, this.password);
  }

  set rawPassword(password: string) {
    this.password = bcrypt.hashSync(password, bcrypt.genSaltSync(10));
  }
}
```

In this example, the data mapper has no knowledge of the `rawPassword` property.

Alternatively, you could use a private field for (de)serialization and provide a getter and setter for use in code:

```typescript
class User {
  @attribute()
  _password?: string;

  checkPassword(password: string): boolean {
    return bcrypt.compareSync(password, this._password);
  }

  get password(): string {
    return this._password;
  }

  set password(password: string) {
    this._password = bcrypt.hashSync(password, bcrypt.genSaltSync(10));
  }
}
```

In this example, the data mapper has no knowledge of the `password` property but will serialize from- and deserialize into the `_password` field.

I don't think baking knowledge of whether a getter and setter is being used into the schema is a good idea. The idea behind getters and setters is that consumers of a class won't know the difference between a regular property and one whose access and mutation is mediated by method invocations.

**Comment by skylerrichter** [comment]
I kind of figure this was the case.

I decided to go with the ladder solution for now.

Thanks again!
