### ISSUE TITLE
Examples for Local Secondary Indexes

### ISSUE THREAD

**Issue by hassankhan** [awslabs/dynamodb-data-mapper-js#93]
Hi there, thanks for creating this project! 😄 

I couldn't seem to see any documentation relating to the use of LSIs, did I potentially miss something or does the project currently not support them?

**Comment by jeskew** [comment]
Hi @hassankhan,

LSIs are fully supported. You can define which attributes of an object are index keys like so:

```typescript
@table('items')
class Item {
  @hashKey({ // <-- this is your normal hash key (shared by table and of LSI)
    indexKeyConfigurations:{
      ItemIdIndex: 'HASH' // The key (ItemIdIndex) is the name of the index; the value is the key type ('HASH' or 'RANGE')
    }
  })
  itemId: string;

  @rangeKey() // <-- this is your normal range key (not part of LSI)
  displayName: string;

  @attribute({
    // And this other attribute acts as the LSI's RangeKey
    indexKeyConfigurations: {
      ItemIdIndex: 'RANGE'
    }
  })
  foo: string;

  @attribute()
  bar: string;
}
```

To query or scan that index, supply the index name when calling `query` or `scan` [as shown in the README](https://github.com/awslabs/dynamodb-data-mapper-js#scan). When reading data, there's no difference from a client-side perspective between local and global secondary indices. You only need to specify whether an index is local or global when creating the table.

**Comment by hassankhan** [comment]
Much appreciated, @jeskew 👍

**Comment by RaviKAG** [comment]
[The issue still exists](https://github.com/awslabs/dynamodb-data-mapper-js/issues/193)

**Comment by TomFrost** [comment]
@jeskew I know I'm years late to the party, but your response has proven exceptionally valuable. I wasn't able to find anything in the documentation about this -- did I miss it? My team has gotten into the habit of adding a `// @see` with this issue URL on each of our models that use multiple indexes. If it's not already in the docs, it would be great to have your response persisted there.
