### ISSUE TITLE
Example for transaction or DocumentClient

### ISSUE THREAD

**Issue by anupareek** [awslabs/dynamodb-data-mapper-js#95]
Hi there, thanks for creating this project! 😄

I had a question regarding use case of saving multiple objects(list) where number of such objects can be greater than 25. Lets call this as List A.  

1. Does this module provide transactional support for me to direct save of parent object followed by saving child object list A? 

2. Can i save an object where my parent object has reference to child object of list A. And this will save my list A along with my parent object in one transaction? 

3. If case 2 is true, then can i send it more than 25 objects for my list A or it need to be less than 25?

Thanks for continuous support !

**Comment by jeskew** [comment]
There's no transaction support in this library.

For questions 2 & 3, does the parent object contain a list of children, or would those children be records in another table?

**Comment by anupareek** [comment]
Hi Jeskew, 

Thanks for the quick response. 
Currently these children are records in another table. However, i can modify my models for any of 2 scenarios. 

For Questions 2 or 3, is there any model way that works?

Thanks!

**Comment by jeskew** [comment]
There’s no reference or pointer type already defined for the mapper, but you can use a `Custom` schema type to capture that use case:

```typescript
const mySchema: Schema = {
    children: {
        type: ‘Custom’,
        marshall(input: ListOfReferences) {
            // convert the input to a DynamoDB AttributeValue
        },
        unmarshall(persisted: AttributeValue) {
             // convert the DynamoDB AttributeValue to the expected shape
        }
    },
    // ... + other properties
}
```

Both `marshall` and `unmarshall` must be synchronous functions, so you would need to save the children before saving the parent. You would want to define the `ListOfReferences` in such a way that it could be saved and hydrated using DynamoDB’s batch methods, and you would probably want to encapsulate the logic saving the children and then the parent in a repository class or data access layer of some kind. If you use the batch methods built into the data mapper, batches will automatically be split into chunks of 25 or fewer records when saving.

If the child records do not reside in another table, no custom logic is required. A record in a DynamoDB table can contain deeply nested lists and maps. This approach is less desirable when multiple parents can contain references to the same child record.

**Comment by anupareek** [comment]
Thanks a lot!
