### ISSUE TITLE
Camel Case vs Pascal Case

### ISSUE THREAD

**Issue by brianjd** [awslabs/dynamodb-data-mapper-js#96]
It is minor, but I'm curious to know the rationale behind the decision to make the annotations camel case rather than pascal.  Either way I'm still looking forward to trying this project out 👍🏽.

**Comment by jeskew** [comment]
No real rationale; the examples in the current [decorators proposal](https://github.com/tc39/proposal-decorators/blob/master/METAPROGRAMMING.md) use camel case and those were what I looked at for conventions when I wrote the annotation functions.

**Comment by brianjd** [comment]
@jeskew Ok, thanks for the insight.  It seems most others have gone with Pascal.  Open to a PR or no?
